# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDescargadeexcel():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_descargadeexcel(self):
    self.driver.get("https://saps4h.gco.com.co/sap/bc/gui/sap/its/webgui/?sap-client=300&sap-language=ES#")
    self.driver.set_window_size(1138, 703)
    self.driver.find_element(By.ID, "sap-user").send_keys("AUXCONMEPA1")
    self.driver.find_element(By.ID, "sap-password").click()
    self.driver.find_element(By.ID, "sap-password").send_keys("auxilarMP01*")
    self.driver.find_element(By.ID, "sap-password").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "ToolbarOkCode").send_keys(Keys.DOWN)
    self.driver.find_element(By.ID, "ToolbarOkCode").send_keys("FAGLL03")
    self.driver.find_element(By.ID, "ToolbarOkCode").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "M0:46:::1:34").send_keys(Keys.DOWN)
    self.driver.find_element(By.ID, "M0:46:::1:34").send_keys("4250060005")
    self.driver.find_element(By.ID, "M0:46:::1:34").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "M0:46:::2:34").click()
    self.driver.find_element(By.ID, "M0:46:::2:34").send_keys(Keys.DOWN)
    self.driver.find_element(By.ID, "M0:46:::2:34").send_keys("1000")
    self.driver.find_element(By.ID, "M0:46:::2:34").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "M0:50::btn[8]").click()
    self.driver.find_element(By.ID, "M1:48::btn[20]").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "UpDownDialogChoose").click()
    self.vars["win6486"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win6486"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])